### ISSUE TITLE
执行route:list报错

### ISSUE THREAD

**Issue by locxiang** [jack15083/laravel-admin#6]
![image](https://user-images.githubusercontent.com/6622033/60155222-19bf8980-981c-11e9-8e1e-58a948cf9840.png)

```
In Container.php line 752:
                                                                  
  Class App\Http\Controllers\Auth\GroupController does not exist  
                                                                  
```

```
[2019-06-26 05:04:00] production.ERROR: Class App\Http\Controllers\Auth\GroupController does not exist {"exception":"[object] (ReflectionException(code: -1): Class App\\Http\\Controllers\\Auth\\GroupController does not exist at /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Container/Container.php:752)
[stacktrace]
#0 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('App\\\\Http\\\\Contro...')
#1 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('App\\\\Http\\\\Contro...')
#2 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Contro...', Array)
#3 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('App\\\\Http\\\\Contro...', Array)
#4 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Route.php(226): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Contro...')
#5 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Route.php(796): Illuminate\\Routing\\Route->getController()
#6 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Route.php(757): Illuminate\\Routing\\Route->controllerMiddleware()
#7 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(151): Illuminate\\Routing\\Route->gatherMiddleware()
#8 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(114): Illuminate\\Foundation\\Console\\RouteListCommand->getMiddleware(Object(Illuminate\\Routing\\Route))
#9 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(86): Illuminate\\Foundation\\Console\\RouteListCommand->getRouteInformation(Object(Illuminate\\Routing\\Route))
#10 [internal function]: Illuminate\\Foundation\\Console\\RouteListCommand->Illuminate\\Foundation\\Console\\{closure}(Object(Illuminate\\Routing\\Route), 2)
#11 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Support/Collection.php(861): array_map(Object(Closure), Array, Array)
#12 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(87): Illuminate\\Support\\Collection->map(Object(Closure))
#13 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(75): Illuminate\\Foundation\\Console\\RouteListCommand->getRoutes()
#14 [internal function]: Illuminate\\Foundation\\Console\\RouteListCommand->handle()
#15 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#16 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#18 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#19 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#20 /Users/xh/app/login-demo/laravel-admin/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 /Users/xh/app/login-demo/laravel-admin/vendor/symfony/console/Application.php(953): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /Users/xh/app/login-demo/laravel-admin/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\RouteListCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /Users/xh/app/login-demo/laravel-admin/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /Users/xh/app/login-demo/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /Users/xh/app/login-demo/laravel-admin/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 {main}
"} 
```

**Comment by jack15083** [comment]
是的在web.php的路由里删掉这个测试路由吧

route::namespace('Auth')->group(function () {
    Route::get('login/ddlogin', 'GroupController@getList');
});
